### ISSUE TITLE
Support the Minimum Common Web Platform API

### ISSUE THREAD

**Issue by saghul** [saghul/txiki.js#418]
https://common-min-api.proposal.wintercg.org/

---

Interfaces:

- [ ] [AbortController](https://dom.spec.whatwg.org/#abortcontroller)
- [ ] [AbortSignal](https://dom.spec.whatwg.org/#abortsignal)
- [ ]  [Blob](https://w3c.github.io/FileAPI/#dfn-Blob)
- [ ]  [ByteLengthQueuingStrategy](https://streams.spec.whatwg.org/#bytelengthqueuingstrategy)
- [ ]  [CompressionStream](https://wicg.github.io/compression/#compression-stream)
- [ ]  [CountQueuingStrategy](https://streams.spec.whatwg.org/#countqueuingstrategy)
- [ ]  [Crypto](https://w3c.github.io/webcrypto/#dfn-Crypto)
- [ ]  [CryptoKey](https://w3c.github.io/webcrypto/#dfn-CryptoKey)
- [ ]  [DecompressionStream](https://wicg.github.io/compression/#decompression-stream)
- [ ]  [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException)
- [ ]  [Event](https://dom.spec.whatwg.org/#event)
- [ ]  [EventTarget](https://dom.spec.whatwg.org/#eventtarget)
- [ ]  [File](https://w3c.github.io/FileAPI/#dfn-file)
- [ ]  [FormData](https://xhr.spec.whatwg.org/#formdata)
- [ ]  [Headers](https://fetch.spec.whatwg.org/#headers)
- [ ]  [ReadableByteStreamController](https://streams.spec.whatwg.org/#readablebytestreamcontroller)
- [ ]  [ReadableStream](https://streams.spec.whatwg.org/#readablestream)
- [ ]  [ReadableStreamBYOBReader](https://streams.spec.whatwg.org/#readablestreambyobreader)
- [ ]  [ReadableStreamBYOBRequest](https://streams.spec.whatwg.org/#readablestreambyobrequest)
- [ ]  [ReadableStreamDefaultController](https://streams.spec.whatwg.org/#readablestreamdefaultcontroller)
- [ ]  [ReadableStreamDefaultReader](https://streams.spec.whatwg.org/#readablestreamdefaultreader)
- [ ]  [Request](https://fetch.spec.whatwg.org/#request)
- [ ]  [Response](https://fetch.spec.whatwg.org/#response)
- [ ]  [SubtleCrypto](https://w3c.github.io/webcrypto/#dfn-SubtleCrypto)
- [ ]  [TextDecoder](https://encoding.spec.whatwg.org/#textdecoder)
- [ ]  [TextDecoderStream](https://encoding.spec.whatwg.org/#textdecoderstream)
- [ ]  [TextEncoder](https://encoding.spec.whatwg.org/#textencoder)
- [ ]  [TextEncoderStream](https://encoding.spec.whatwg.org/#textencoderstream)
- [ ]  [TransformStream](https://streams.spec.whatwg.org/#transformstream)
- [ ]  [TransformStreamDefaultController](https://streams.spec.whatwg.org/#transformstreamdefaultcontroller)
- [ ]  [URL](https://url.spec.whatwg.org/#url)
- [ ]  [URLSearchParams](https://url.spec.whatwg.org/#urlsearchparams)
- [ ]  [WebAssembly.Global](https://webassembly.github.io/spec/js-api/#global)
- [ ]  [WebAssembly.Instance](https://webassembly.github.io/spec/js-api/#instance)
- [ ]  [WebAssembly.Memory](https://webassembly.github.io/spec/js-api/#memory)
- [ ]  [WebAssembly.Module](https://webassembly.github.io/spec/js-api/#module)
- [ ]  [WebAssembly.Table](https://webassembly.github.io/spec/js-api/#table)
- [ ]  [WritableStream](https://streams.spec.whatwg.org/#writablestream)
- [ ]  [WritableStreamDefaultController](https://streams.spec.whatwg.org/#writablestreamdefaultcontroller)

Global methods / properties:

- [ ]  [globalThis](https://tc39.es/ecma262/multipage/global-object.html#sec-globalthis)
- [ ]  globalThis.[atob()](https://html.spec.whatwg.org/multipage/webappapis.html#dom-atob)
- [ ]  globalThis.[btoa()](https://html.spec.whatwg.org/multipage/webappapis.html#dom-btoa)
- [ ]  globalThis.[console](https://console.spec.whatwg.org/#namespacedef-console)
- [ ]  globalThis.[crypto](https://w3c.github.io/webcrypto/#dom-windoworworkerglobalscope-crypto)
- [ ]  globalThis.[fetch()](https://wicg.github.io/background-fetch/#dom-backgroundfetchmanager-fetch)
- [ ]  globalThis.[navigator](https://html.spec.whatwg.org/multipage/system-state.html#dom-navigator).[userAgent](https://html.spec.whatwg.org/multipage/system-state.html#dom-navigator-useragent)
- [ ]  globalThis.[performance](https://w3c.github.io/hr-time/#dom-windoworworkerglobalscope-performance).[now()](https://w3c.github.io/hr-time/#dom-performance-now)
- [ ]  globalThis.[performance](https://w3c.github.io/hr-time/#dom-windoworworkerglobalscope-performance).[timeOrigin](https://w3c.github.io/hr-time/#dom-performance-timeorigin)
- [ ]  globalThis.[queueMicrotask()](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-queuemicrotask)
- [ ]  globalThis.[setTimeout()](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-settimeout) / globalThis.[clearTimeout()](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-cleartimeout)
- [ ]  globalThis.[setInterval()](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-setinterval) / globalThis.[clearInterval()](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-clearinterval)
- [ ]  globalThis.[structuredClone()](https://html.spec.whatwg.org/multipage/structured-data.html#dom-structuredclone)
- [ ]  globalThis.[WebAssembly](https://webassembly.github.io/spec/js-api/#namespacedef-webassembly).[compile()](https://webassembly.github.io/spec/js-api/#dom-webassembly-compile)
- [ ]  globalThis.[WebAssembly](https://webassembly.github.io/spec/js-api/#namespacedef-webassembly).[compileStreaming()](https://webassembly.github.io/spec/web-api/#dom-webassembly-compilestreaming)
- [ ]  globalThis.[WebAssembly](https://webassembly.github.io/spec/js-api/#namespacedef-webassembly).[instantiate()](https://webassembly.github.io/spec/js-api/#dom-webassembly-instantiate)
- [ ]  globalThis.[WebAssembly](https://webassembly.github.io/spec/js-api/#namespacedef-webassembly).[instantiateStreaming()](https://webassembly.github.io/spec/web-api/#dom-webassembly-instantiatestreaming)
- [ ]  globalThis.[WebAssembly](https://webassembly.github.io/spec/js-api/#namespacedef-webassembly).[validate()](https://webassembly.github.io/spec/js-api/#dom-webassembly-validate)

**Comment by bnoordhuis** [comment]
To avoid duplication across embedders, atob, btoa, structuredClone<sup>1</sup>, queueMicrotask and performance could be implemented as quickjs-ng C APIs or JS globals. We'd also have to add DOMException but that seems okay to me. We can make them opt-in when the JSContext is created.
 
Thoughts?

<sup>1</sup> TBD how to handle transferables

**Comment by saghul** [comment]
Yep makes sense to me, let's do that!

**Comment by jimmywarting** [comment]
https://github.com/saghul/txiki.js/blob/c7c5aa988356751051f748485db010cee219b446/src/js/polyfills/blob.js#L1-L8

For a better Blob and File polyfill I would recommend taking a look at [fetch-blob](https://github.com/node-fetch/fetch-blob)

**Comment by saghul** [comment]
Thanks!

**Comment by guest271314** [comment]
`navigator.userAgent`. See https://github.com/wintercg/proposal-common-minimum-api/issues/62.

**Comment by saghul** [comment]
> `navigator.userAgent`. See [wintercg/proposal-common-minimum-api#62](https://github.com/wintercg/proposal-common-minimum-api/issues/62).

Done in https://github.com/saghul/txiki.js/pull/439

**Comment by guest271314** [comment]
Ehe WinterCG folks banned me from over there at Minimum Common world already. No notice, no reason given. Weak. Anyway, carry on.

**Comment by saghul** [comment]
Again, it's Response what's broken / non-compliant.

**Comment by saghul** [comment]
Stop it. The spec is a living document, not all features are supported.

**Comment by guest271314** [comment]
> Stop it. The spec is a living document, not all features are supported.

Really?

You know `Response` is broken in `tjs` yet you still have the box checked? That's how we're rolling in txiki.js world? That's the standard?

**Comment by guest271314** [comment]
What that means is that the txiki.js documentation is unreliable. A checkbox only has two states, true and false. You don't have `crypto` checked. That's true and correct. `Response` being checked is false. There's no asterisk next to the `Response` checkbox with details about what is broken, and the roadmap to fixing what's broken. Somebody rolls up and read that and thinks `Response` in `tjs` will work as intended, and it doesn't. We should have clarity and transparency and honesty about what's going on; from the inside out. Thanks.
